# 构建阶段
FROM nginx:stable-perl

WORKDIR /app

# 复制nginx配置文件
COPY ./frontend/nginx/nginx.conf /etc/nginx/nginx.conf

# 复制构建好的文件
COPY ./frontend/web/dist/ /usr/share/nginx/html/
RUN chmod -R 755 /usr/share/nginx/html/

# 复制日志目录
RUN mkdir -p /var/log/nginx

# 暴露端口
EXPOSE 80

# 启动nginx
CMD ["nginx", "-g", "daemon off;"]
